name: "attic"
description: "Cache Nix derivations with attic"

inputs:
  endpoint:
    description: "attic endpoint"
    required: true
  cache:
    description: "attic cache"
    required: true
  skip-push:
    description: "set to true to disable pushing to the cache"
    required: false
  token:
    description: "attic token"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
